config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from user.views import (register, userlogin, userlogout, unavailable, feedback, report_issue, handler404)
from polls.views import homepageview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepageview, name="homepage"),
    path('polls/', include('polls.urls')),
    path('forums/', include('forums.urls')),
    path('register/', register, name='register'),
    path('login/', userlogin, name='login'),
    path('logout/', userlogout, name='logout'),
    path('sourcecode/', unavailable, name='sourcecode'),
    path('rules/', unavailable, name='rules'),
    path('issue/', report_issue, name='issue'),
    path('feedback/', feedback, name='feedback'),
    path('about/', unavailable, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'user.views.handler404'

forums/urls.py
from django.urls import path
from forums import views

app_name = 'forums'

urlpatterns = [
    path('', views.forums_all, name="forum_all"),
    path('editpost/', views.edit_post, name="post_edit"),
    path('updatepost/', views.update_post, name="post_update"),
    path('deletepost/<int:pk>', views.delete_post, name="post_delete"),
    path('create/', views.forum_create, name="forum_create"),
    path('<int:pk>/', views.forumdetail, name="forum_detail"),
    path('<int:pk>/edit', views.edit_forum, name="edit_forum"),
    path('<int:pk>/reply/', views.reply_to_forum, name="forum_reply"),
]

polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.pollshomepage, name='index'),
    path('browse/', views.polls_all, name='browse'),
    path('<int:pk>/', views.polldetail , name='polldetails'),
    path('<int:pk>/edit', views.update_poll , name='edit_poll'),
    path('<int:pk>/vote/', views.vote_now , name='vote'),
    path('create/', views.create_poll , name='create_poll'),
    path('vote/history', views.votes_history , name='votes_history'),
]

forums/models.py
from django.db import models
from django.contrib.auth.models import User


class ForumTopic(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='forum')
    active = models.BooleanField(default=True)
    locked = models.BooleanField(default=False)
    added = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

class Post(models.Model):
    post_text = models.TextField()
    forum = models.ForeignKey(ForumTopic, on_delete=models.CASCADE, related_name='forumpost')
    post_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userpost')
    added = models.DateTimeField()
    updated = models.DateTimeField()

    def __str__(self):
        return f"forum({self.forum}) post"

forums/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from forums.models import (ForumTopic, Post)
from django.core.paginator import Paginator
import datetime
from polls.views import (get_polls_panel_context, get_forum_panel_context)
from django.contrib.auth.decorators import login_required
from polls.views import renderError
from django.utils import timezone

@login_required
def forums_all(request):
    forums_raw = ForumTopic.objects.all().order_by('-added')
    paginator_forums = Paginator(forums_raw, 10)
    page_no = request.GET.get('page')
    forums = paginator_forums.get_page(page_no)
    forums_all_context = dict()
    forums_all_context['forum_panel'] = get_forum_panel_context(request)
    forums_all_context['recentpolls'] = get_polls_panel_context(request)
    forums_all_context['username'] = request.user.username
    forum_topics = []
    for forum in forums:
        unit_context = dict()
        unit_context['forum_id'] = forum.id
        unit_context['title'] = forum.title
        allPosts = forum.forumpost.all().order_by('added')
        firstPost = allPosts[0]
        lastPost = forum.forumpost.latest('added')
        unit_context['views'] = forum.views
        unit_context['first_post_text'] = firstPost.post_text
        unit_context['num_replies'] = allPosts.count() - 1
        unit_context['last_post_time'] = forum.added
        forum_topics.append(unit_context)
    forums_all_context['forums'] = forum_topics
    paginator_context = dict()
    paginator_context['has_more_pages'] = forums.has_previous() or forums.has_next()
    paginator_context['has_next'] = forums.has_next()
    paginator_context['has_previous'] = forums.has_previous()
    paginator_context['current_page'] = forums.number
    paginator_context['total_pages'] = forums.paginator.num_pages
    paginator_context['prev_page_num'] = forums.previous_page_number
    paginator_context['next_page_num'] = forums.next_page_number
    forums_all_context['paginator'] = paginator_context

    return render(request, 'forums/forums_all.html', context=forums_all_context)


@login_required
def forumdetail(request, pk):
    try:
        forum = ForumTopic.objects.get(pk=pk)
    except ForumTopic.DoesNotExist:
        return renderError(request, '(404) Forum Not Found')
    if not forum.active:
        return renderError(request, '(403) Forum Restricted')
    forumViews = forum.views + 1
    ForumTopic.objects.filter(pk=pk).update(views=forumViews)
    forum_detail_context = dict()
    forum_detail_context['forum_panel'] = get_forum_panel_context(request)
    forum_detail_context['recentpolls'] = get_polls_panel_context(request)
    forum_detail_context['username'] = request.user.username
    forum_detail_context['forum_id'] = forum.id
    forum_detail_context['edit_permit'] = (forum.author == request.user ) or request.user.is_staff
    forum_detail_context['topic_title'] = forum.title
    forum_detail_context['lock_status'] = forum.locked
    forumPosts_raw = forum.forumpost.all()
    forum_paginator = Paginator(forumPosts_raw, 5)
    page_no = request.GET.get('page')
    forumPosts = forum_paginator.get_page(page_no)
    posts_context = []
    for post in forumPosts:
        unit_context = dict()
        unit_context['author'] = post.post_author
        unit_context['added'] = post.added
        unit_context['text'] = post.post_text
        if post.added != post.updated:
            unit_context['updated'] = post.updated
        if post.post_author == request.user:
            unit_context['own_post'] = True
            unit_context['post_id'] = post.id
        posts_context.append(unit_context)
    forum_detail_context['posts'] = posts_context
    paginator_context = dict()
    paginator_context['has_more_pages'] = forumPosts.has_previous() or forumPosts.has_next()
    paginator_context['has_next'] = forumPosts.has_next()
    paginator_context['has_previous'] = forumPosts.has_previous()
    paginator_context['current_page'] = forumPosts.number
    paginator_context['total_pages'] = forumPosts.paginator.num_pages
    paginator_context['prev_page_num'] = forumPosts.previous_page_number
    paginator_context['next_page_num'] = forumPosts.next_page_number
    forum_detail_context['paginator'] = paginator_context
    return render(request, 'forums/forum_detail.html', context=forum_detail_context)


@login_required
def reply_to_forum(request, pk):
    if request.method == 'GET':
        return redirect('forums:forum_detail', pk=pk)
    else:
        reply_text = request.POST.get('reply-text', False)
        if not reply_text:
            polls_panel_context = get_polls_panel_context(request)
            forums_panel_context = get_forum_panel_context(request)
            username = request.user.username
            context = {'username':username,'recentpolls': polls_panel_context, 'forums': forums_panel_context, 'error':'Cannot Post Empty Reply'}
            return render(request, 'polls/error.html', context=context)
        forum_topic = get_object_or_404(ForumTopic, pk=pk)
        if forum_topic.locked == True or forum_topic.active != True:
            polls_panel_context = get_polls_panel_context(request)
            forums_panel_context = get_forum_panel_context(request)
            username = request.user.username
            context = {'username':username, 'recentpolls': polls_panel_context, 'forums': forums_panel_context, 'error':'Topic Is Locked/Inactive'}
            return render(request, 'polls/error.html', context=context)
        time_now = timezone.now()   
        post = Post.objects.create(post_text=reply_text, forum=forum_topic, added=time_now, updated=time_now, post_author=request.user)
        post.save()
        return redirect('forums:forum_detail', pk=pk)


@login_required
def forum_create(request):
    if request.method == "GET":
        polls_panel = get_polls_panel_context(request)
        forums_panel = get_forum_panel_context(request)
        username = request.user.username
        return render(request, 'forums/forum_create.html', context={'username':username,'recentpolls':polls_panel, 'forums':forums_panel})
    else:
        forum_kwargs = dict()
        forum_kwargs['title'] = request.POST.get('topic')
        forum_kwargs['author'] = request.user
        new_forum = ForumTopic.objects.create(**forum_kwargs)
        new_forum.save()
        post_kwargs = dict()
        post_kwargs['post_text'] = request.POST.get('post-text')
        post_kwargs['forum'] = new_forum
        time_now = timezone.now()
        post_kwargs['added'] = time_now
        post_kwargs['updated'] = time_now
        post_kwargs['post_author'] = request.user
        new_post = Post.objects.create(**post_kwargs)
        new_post.save()
        return redirect('forums:forum_detail', pk=new_forum.id)


@login_required
def edit_forum(request, pk):
    if request.method == 'GET':
        try:
            forum = ForumTopic.objects.get(pk=pk)
        except ForumTopic.DoesNotExist:
            return renderError(request, "(404) Forum Not Found")
        edit_permit = (request.user == forum.author) or request.user.is_staff
        if not edit_permit:
            return renderError(request, "(403) Access Denied")
        if not forum.active:
            return renderError(request, "Restricted Forum")
        edit_forum_context = dict()
        edit_forum_context['recentpolls'] = get_polls_panel_context(request)
        edit_forum_context['forum_panel'] = get_forum_panel_context(request)
        edit_forum_context['forum_id'] = forum.id
        edit_forum_context['forum_title'] = forum.title
        firstPost = forum.forumpost.all().order_by('added')[0]
        edit_forum_context['post_text'] = firstPost.post_text
        return render(request, 'forums/forum_edit.html', context=edit_forum_context)
    else:
        try:
            forum = ForumTopic.objects.get(pk=pk)
        except ForumTopic.DoesNotExist:
            return renderError(request, "(404) Forum Not Found")
        title = request.POST.get('topic')
        post_text = request.POST.get('post-text')
        if not bool(title) or not bool(post_text):
            return renderError(request, "Empty Input Field")
        forum.title = title
        firstPost = forum.forumpost.all().order_by('added')[0]
        firstPost.post_text = post_text
        forum.save()
        firstPost.save()
        return redirect('forums:forum_detail', pk=pk)
        
    

@login_required
def edit_post(request):
    if request.method == 'GET':
        return redirect('forums:forum_all')
    else:
        post_pk = request.POST.get('post_id')
        if not bool(post_pk):
            return redirect('forums:forum_all')
        try:
            post = Post.objects.get(pk=post_pk)
        except Post.DoesNotExist:
            return renderError(request, 'Post Not Found')  
        if post.post_author != request.user:
            return renderError(request, 'Unauthorized')
        edit_post_context = {}
        edit_post_context['username'] = request.user.username
        edit_post_context['recentpolls'] = get_polls_panel_context(request)
        edit_post_context['forum_panel'] = get_forum_panel_context(request)
        edit_post_context['forum_id'] = post.forum.id
        edit_post_context['forum_title'] = post.forum.title
        edit_post_context['post_id'] = post.id
        edit_post_context['prev_post_text'] = post.post_text
        return render(request, 'forums/forum_post_edit.html', context=edit_post_context)


@login_required
def update_post(request):
    if request.method == 'GET':
        return redirect('forums:forum_all')
    else:
        post_pk = request.POST.get('pk')
        try:
            post = Post.objects.get(pk=post_pk)
        except Post.DoesNotExist:
            return renderError(request, "Invalid Request")
        if post.post_author != request.user:
            return renderError(request, "Unauthorized")

forums/templates/forums/forum_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/r.png' %}">
    <title>View Forum</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand ms-5 pe-3" href="{% url 'homepage' %}"><span class="r">r</span>Polls</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-1">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:browse' %}">Polls</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:create_poll' %}">Create poll</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_all' %}">Forums</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_create' %}">New forum</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:votes_history' %}">Vote history</a>
                  </li>
                </ul>
                <div class="account d-flex me-4">
                    <div class="profile d-flex my-auto me-3">
                        <i class="bi bi-person-circle"></i>
                        <span class="username-viewonly ms-1">{{ username }}</span>
                    </div>
                    <form action="{% url 'logout' %}" method="POST"> {% csrf_token %}
                        <input type="submit" class="btn-1" value="Logout">
                    </form>
                </div>
              </div>
            </div>
          </nav>
    </header>
    <div class="main-container">
        <div class="left-col">
            <div class="recent-polls card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-activity"></i></span>
                    <span class="title">Most Recent</span>
                </div>
                <div class="content">
                    {% for poll in recentpolls %}
                    <div class="poll-item">
                        <a class="poll-title" href="{% url 'polls:polldetails' poll.poll_id %}">{{ poll.poll_title }}</a>
                        <div class="count">
                            <span class="label">vote count:&nbsp;</span><span class="value">{{ poll.vote_count }}</span>
                        </div>
                        {% if poll.vote_count%}
                        <div class="last-vote">
                            <span class="label"><i class="bi bi-check-all"></i></span>
                            <span class="date">{{ poll.last_vote_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ poll.last_vote_voter }}</span>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <a href="{% url 'polls:browse' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
            <div class="community-forum card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-chat-right"></i></span>
                    <span class="title">Forums</span>
                </div>
                <div class="content">
                    {% for forum in forum_panel %}
                    <div class="forum-post">
                        <a class="post-title" href="{% url 'forums:forum_detail' forum.forum_id %}">{{ forum.forum_title }}</a>
                        <div class="last-post">
                            <span class="label"><i class="bi bi-arrow-90deg-down"></i></span>
                            <span class="date">{{ forum.last_post_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ forum.last_post_user }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a href="{% url 'forums:forum_all' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
        </div>
        <div class="right-col">
            <div class="forum-detail card">
                <div class="heading">
                    <i class="bi bi-chat-right me-1"></i>
                    <span class="title">{{ topic_title }}{% if edit_permit %}<a href="{% url 'forums:edit_forum' forum_id %}"><i class="bi bi-pencil-fill"></i></a>{% endif %}</span>
                </div>
                <div class="content">
                    {% for post in posts %}
                    <div class="forum-post">
                        <div class="user">
                            <div class="username">{{ post.author }}</div>
                            <div class="post-time">{{ post.added|date:"h:i A, j M o" }}</div>
                        </div>
                        <div class="post-body">
                            <div class="content"><p>{{ post.text|safe|linebreaks }}</p></div>
                            <div class="action">
                                {% if post.updated %}<span class="last-edited"><i class="bi bi-arrow-clockwise"></i>last edited: {{ post.updated|date:"h:i:s A, j M o" }}</span>{% endif %}
                                {% if post.own_post %}
                                <form action="{% url 'forums:post_edit' %}" id="edit_post{{ post.post_id }}" style="display:inline;" method="POST"> {% csrf_token %}
                                    <input type="hidden" name="post_id" value="{{ post.post_id }}">
                                    <button onclick="document.getElementById('edit_post').submit()"><i class="bi bi-pencil-fill"></i></button>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% if paginator.has_more_pages %}
                    <div class="paginator">
                        <div class="inner">
                            <ul>
                                {% if paginator.has_previous %}<a href="?page={{ paginator.prev_page_num }}"><li>&#8592;</li></a>{% endif %}
                                <li>page&nbsp;{{ paginator.current_page }}&nbsp;of&nbsp;{{ paginator.total_pages }}</li>
                                {% if paginator.has_next %}<a href="?page={{ paginator.next_page_num }}"><li>&#8594;</li></a>{% endif %}
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                    <div class="reply-wrapper">
                        {% if lock_status %}
                        <div class="locked_status_container">
                            <div class="inner">
                                <div>
                                    <i class="bi bi-lock"></i>
                                    <span>Forum Locked</span>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <form action="{% url 'forums:forum_reply' forum_id %}" class="reply" method="POST">{% csrf_token %}
                            <textarea name="reply-text" id="reply-text" class="textinput" placeholder="Reply Text"></textarea>
                            <input type="submit" class="btn-1" value="Reply">
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="upper">
            <div class="col-1">
                <div class="site-name">
                    <span class="r">r</span>Polls</a>
                </div>
            </div>
            <div class="vl"></div>
            <div class="col-2">
                <a href="{% url 'rules' %}">Site Rules</a>
                <a href="{% url 'issue' %}"><i class="bi bi-flag-fill"></i>Report an issue</a>
            </div>
            <div class="vl"></div>
            <div class="col-3">
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'feedback' %}"><i class="bi bi-chat-square-dots-fill"></i>Feedback</a>
                <a href="{% url 'sourcecode' %}"><i class="bi bi-github"></i>Project Sourcecode</a>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

forums/templates/forums/forum_post_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/r.png' %}">
    <title>Edit post</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand ms-5 pe-3" href="{% url 'homepage' %}"><span class="r">r</span>Polls</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-1">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:browse' %}">Polls</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:create_poll' %}">Create poll</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_all' %}">Forums</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_create' %}">New forum</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:votes_history' %}">Vote history</a>
                  </li>
                </ul>
                <div class="account d-flex me-4">
                    <div class="profile d-flex my-auto me-3">
                        <i class="bi bi-person-circle"></i>
                        <span class="username-viewonly ms-1">{{ username }}</span>
                    </div>
                    <form action="{% url 'logout' %}" method="POST"> {% csrf_token %}
                        <input type="submit" class="btn-1" value="Logout">
                    </form>
                </div>
              </div>
            </div>
          </nav>
    </header>
    <div class="main-container">
        <div class="left-col">
            <div class="recent-polls card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-activity"></i></span>
                    <span class="title">Most Recent</span>
                </div>
                <div class="content">
                    {% for poll in recentpolls %}
                    <div class="poll-item">
                        <a class="poll-title" href="{% url 'polls:polldetails' poll.poll_id %}">{{ poll.poll_title }}</a>
                        <div class="count">
                            <span class="label">vote count:&nbsp;</span><span class="value">{{ poll.vote_count }}</span>
                        </div>
                        {% if poll.vote_count%}
                        <div class="last-vote">
                            <span class="label"><i class="bi bi-check-all"></i></span>
                            <span class="date">{{ poll.last_vote_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ poll.last_vote_voter }}</span>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <a href="{% url 'polls:browse' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
            <div class="community-forum card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-chat-right"></i></span>
                    <span class="title">Forums</span>
                </div>
                <div class="content">
                    {% for forum in forum_panel %}
                    <div class="forum-post">
                        <a class="post-title" href="{% url 'forums:forum_detail' forum.forum_id %}">{{ forum.forum_title }}</a>
                        <div class="last-post">
                            <span class="label"><i class="bi bi-arrow-90deg-down"></i></span>
                            <span class="date">{{ forum.last_post_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ forum.last_post_user }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a href="{% url 'forums:forum_all' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
        </div>
        <div class="right-col">
            <div class="create-forum card">
                <div class="heading">
                    <i class="bi bi-pencil me-1"></i>
                    <span class="title">Edit Post</span>
                </div>
                <div class="form-wrapper">
                    <form action="{% url 'forums:post_update' %}" method="POST"> {% csrf_token %}
                        <div class="fi t-name mb-3">
                            <h5>{{ forum_title }}</h5>
                        </div>
                        <div class="fi post-body">
                            <textarea name="post-text" class="textinput" id="post-text" placeholder="Post Body" required="">{{ prev_post_text }}</textarea>
                            <input type="hidden" name="pk" value="{{ post_id }}">
                            <input type="hidden" name="forum_pk" value="{{ forum_id }}">
                        </div>
                        <div class="fi submit">
                            <div class="inner">
                                <a href="{% url 'forums:post_delete' post_id %}" style="display:inline;" class="me-2" onclick="return confirm('Confirm deletion')"><i class="bi bi-trash3"></i></a>
                                <input type="submit" class="btn-1" value="Update">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="upper">
            <div class="col-1">
                <div class="site-name">
                    <span class="r">r</span>Polls</a>
                </div>
            </div>
            <div class="vl"></div>
            <div class="col-2">
                <a href="{% url 'rules' %}">Site Rules</a>
                <a href="{% url 'issue' %}"><i class="bi bi-flag-fill"></i>Report an issue</a>
            </div>
            <div class="vl"></div>
            <div class="col-3">
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'feedback' %}"><i class="bi bi-chat-square-dots-fill"></i>Feedback</a>
                <a href="{% url 'sourcecode' %}"><i class="bi bi-github"></i>Project Sourcecode</a>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>