config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from user.views import (register, userlogin, userlogout, unavailable, feedback, report_issue, handler404)
from polls.views import homepageview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepageview, name="homepage"),
    path('polls/', include('polls.urls')),
    path('forums/', include('forums.urls')),
    path('register/', register, name='register'),
    path('login/', userlogin, name='login'),
    path('logout/', userlogout, name='logout'),
    path('sourcecode/', unavailable, name='sourcecode'),
    path('rules/', unavailable, name='rules'),
    path('issue/', report_issue, name='issue'),
    path('feedback/', feedback, name='feedback'),
    path('about/', unavailable, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'user.views.handler404'

forums/urls.py
from django.urls import path
from forums import views

app_name = 'forums'

urlpatterns = [
    path('', views.forums_all, name="forum_all"),
    path('editpost/', views.edit_post, name="post_edit"),
    path('updatepost/', views.update_post, name="post_update"),
    path('deletepost/<int:pk>', views.delete_post, name="post_delete"),
    path('create/', views.forum_create, name="forum_create"),
    path('<int:pk>/', views.forumdetail, name="forum_detail"),
    path('<int:pk>/edit', views.edit_forum, name="edit_forum"),
    path('<int:pk>/reply/', views.reply_to_forum, name="forum_reply"),
]

polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.pollshomepage, name='index'),
    path('browse/', views.polls_all, name='browse'),
    path('<int:pk>/', views.polldetail , name='polldetails'),
    path('<int:pk>/edit', views.update_poll , name='edit_poll'),
    path('<int:pk>/vote/', views.vote_now , name='vote'),
    path('create/', views.create_poll , name='create_poll'),
    path('vote/history', views.votes_history , name='votes_history'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

class Poll(models.Model):
    title = models.CharField(max_length=250)
    banner = models.ImageField(upload_to='polls/images/', default='polls/images/default.jpg')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='poll')
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    added = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Choice(models.Model):
    choicetext = models.CharField(max_length=100)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='choice')

    def __str__(self):
        return self.choicetext


class Vote(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, related_name='choicevote')
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='pollvote')
    voter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uservote')
    vote_time = models.DateTimeField(auto_now_add=True)
    vote_update_time = models.DateTimeField(auto_now=True)

polls/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from polls.models import (Poll, Choice, Vote)
from forums.models import (ForumTopic, Post)
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import os


def homepageview(request):
    if request.user.is_authenticated:
        return redirect('polls:index')
    return render(request, 'polls/home.html')


def get_forum_panel_context(request):
    recentforums = ForumTopic.objects.filter(active=True).order_by('-added')[:5]
    recentforums_context = []
    for forum in recentforums:
        forum_id = forum.id
        forum_title = forum.title
        lastPost = forum.forumpost.latest('added')
        last_post_time = lastPost.added
        last_post_user = lastPost.post_author
        unit_context = {'forum_id': forum_id, 'forum_title': forum_title, 'last_post_time': last_post_time, 'last_post_user': last_post_user}
        recentforums_context.append(unit_context)
    return recentforums_context


def get_polls_panel_context(request):
    recentpolls = Poll.objects.filter(public=True, active=True, visible=True).order_by('-added')[:5]
    recentpolls_context = []
    for poll in recentpolls:
        poll_id = poll.id
        poll_title = poll.title
        try:
            vote_count = poll.pollvote.count()
            lastVote = poll.pollvote.latest('vote_time')
        except Vote.DoesNotExist:
            unit_context = {'poll_id': poll_id, 'poll_title': poll_title, 'vote_count': 0}
            recentpolls_context.append(unit_context)
            continue
        last_vote_time = lastVote.vote_time
        last_vote_voter = lastVote.voter
        unit_context = {'poll_id': poll_id, 'poll_title': poll_title, 'vote_count': vote_count,
                        'last_vote_time': last_vote_time, 'last_vote_voter': last_vote_voter}
        recentpolls_context.append(unit_context)
    return recentpolls_context


def renderError(request, error_msg):
    context = {}
    context['username'] = request.user.username
    context['recentpolls'] = get_polls_panel_context(request)
    context['forums'] = get_forum_panel_context(request)
    context['error'] = error_msg
    return render(request, 'polls/error.html', context=context)


@login_required()
def pollshomepage(request):
    username = request.user.username
    recentpolls_context = get_polls_panel_context(request)
    # forums panel context
    recentforums_context = get_forum_panel_context(request)
    #user's polls
    recentpolls_user = Poll.objects.filter(author=request.user, visible=True).order_by('-added')
    recentpolls_user_context = []
    paginator_context = dict()
    if recentpolls_user.count() > 0:
        paginator = Paginator(recentpolls_user, 5)
        page_no = request.GET.get('page')
        pollspage = paginator.get_page(page_no)
        for poll in pollspage:
            poll_id = poll.id
            poll_title = poll.title
            poll_views = poll.views
            active_status = poll.active
            try:
                vote_count = poll.pollvote.count()
                lastVote = poll.pollvote.latest('vote_time')
            except Vote.DoesNotExist:
                unit_context = {'poll_id': poll_id, 'poll_views': poll_views, 'active_status': active_status, 
                                'poll_title': poll_title, 'vote_count': 0}
                recentpolls_user_context.append(unit_context)
                continue
            last_vote_time = lastVote.vote_time
            unit_context = {'poll_id': poll_id, 'poll_title': poll_title, 'vote_count': vote_count, 'poll_views': poll_views,
                            'active_status': active_status, 'last_vote_time': last_vote_time}
            recentpolls_user_context.append(unit_context)
        current_page = pollspage.number
        total_page = pollspage.paginator.num_pages
        has_more_page = pollspage.has_previous() or pollspage.has_next()
        has_prev = pollspage.has_previous()
        has_next = pollspage.has_next()
        next_page_num = current_page + 1
        prev_page_num = current_page - 1
        paginator_context = {'current_page': current_page, 'total_page': total_page, 'has_more_page': has_more_page,
                                    'has_prev': has_prev, 'has_next': has_next, 'next_page_num': next_page_num, 'prev_page_num': prev_page_num} 

    #user stats panel
    stat_context = dict()
    try:
        userCreatedPolls = Poll.objects.filter(author=request.user)
        user_vote_gain = 0
        for userpoll in userCreatedPolls:
            pollVotes = userpoll.pollvote.count()
            user_vote_gain += pollVotes
        stat_context['user_vote_gain'] = user_vote_gain
    except:
        pass
    try:
        stat_context['user_created_active_polls'] = Poll.objects.filter(author=request.user, active=True).count()
        stat_context['user_created_poll_nums'] = userCreatedPolls.count()
    except:
        pass
    try:
        recentPoll = Poll.objects.filter(author=request.user).order_by('-added')[0]
        stat_context['recent_poll_id'] = recentPoll.id
        stat_context['recent_poll_title'] = recentPoll.title
    except:
        pass  
    try:
        userVotes = Vote.objects.filter(voter=request.user).order_by('-vote_time')
        stat_context['users_vote_count'] = userVotes.count()
        userLastVote = userVotes[0]
        stat_context['user_last_vote_time'] = userLastVote.vote_time
        stat_context['user_last_vote_poll_id'] = userLastVote.poll.id
        stat_context['user_last_vote_poll_title'] = userLastVote.poll.title
    except:
        pass

    return render(request, 'polls/index.html', context={'recentpolls': recentpolls_context, 'forums': recentforums_context, 
                                                        'recentpolls_user': recentpolls_user_context, 'username':username,
                                                        'paginator': paginator_context, 'stat': stat_context})


@login_required()
def polldetail(request, pk):
    polldetail_context = dict()
    try:
        poll = Poll.objects.get(pk=pk)
    except Poll.DoesNotExist:
        return renderError(request, '(404) Poll Not Found')
    if not poll.visible:
        return renderError(request, 'Only Admins Can Access')
    user_voted = bool(poll.pollvote.filter(voter=request.user).count())
    view_permitted_user = (poll.author == request.user) or (request.user.is_staff)
    if poll.active and not user_voted and not view_permitted_user:
        return redirect('polls:vote', pk=pk)
    polldetail_context['votable_status'] = view_permitted_user and (not user_voted) and (poll.active)
    polldetail_context['recentpolls'] = get_polls_panel_context(request)
    polldetail_context['forums'] = get_forum_panel_context(request)
    polldetail_context['username'] = request.user.username
    pollViews = poll.views + 1
    Poll.objects.filter(pk=pk).update(views=pollViews)
    polldetail_context['poll_id'] = poll.id
    polldetail_context['poll_url'] = request.build_absolute_uri()
    polldetail_context['poll_title'] = poll.title
    polldetail_context['poll_author'] = poll.author
    polldetail_context['editable'] = (poll.author == request.user) or (request.user.is_staff)
    polldetail_context['poll_added'] = poll.added
    polldetail_context['poll_views'] = pollViews
    polldetail_context['is_active_poll'] = poll.active
    if poll.active:
        polldetail_context['active_status'] = 'active'
    else:
        polldetail_context['active_status'] = 'inactive'
    
    try:
        myVote = poll.pollvote.get(voter=request.user)
        polldetail_context['my_vote_time'] = myVote.vote_time
    except Exception:
        pass
    try:
        lastVote = poll.pollvote.latest('vote_time')
        polldetail_context['last_vote_time'] = lastVote.vote_time
        polldetail_context['last_vote_voter'] = lastVote.voter
    except Exception:
        pass
    polldetail_context['poll_banner_url'] = poll.banner.url
    poll_choices = poll.choice.all()
    total_votes = poll.pollvote.count()
    choices_context = []
    for choice in poll_choices:
        choice_text = choice.choicetext
        choice_votes = choice.choicevote.count()
        try:
            percentVotes = (choice_votes/total_votes)*100
        except ZeroDivisionError:
            percentVotes = 0
        choice_votes_percent = round(percentVotes, 2)
        progressbar_progress = round(percentVotes)
        is_voted = bool(choice.choicevote.filter(voter=request.user).count())
        unit_context = {'choice_text':choice_text, 'choice_votes':choice_votes, 'choice_votes_percent':choice_votes_percent,
                        'progressbar_progress':progressbar_progress, 'is_voted':is_voted}
        choices_context.append(unit_context)
    polldetail_context['choices'] = choices_context
    polldetail_context['total_votes'] = total_votes
    return render(request, 'polls/poll_detail.html', context=polldetail_context)


@login_required()
def polls_all(request):
    polls_all_raw = Poll.objects.filter(public=True, active=True, visible=True).order_by('-added')
    polls_paginator = Paginator(polls_all_raw, 5)
    page_no = request.GET.get('page')
    page_polls = polls_paginator.get_page(page_no)
    browse_poll_context = dict()
    browse_poll_context['username'] = request.user.username
    polls_context = []
    for poll in page_polls:
        unit_context = dict()
        unit_context['poll_id'] = poll.id
        unit_context['poll_title'] = poll.title
        unit_context['vote_count'] = poll.pollvote.count()
        unit_context['added'] = poll.added
        unit_context['author'] = poll.author
        unit_context['title'] = poll.pollvote.count()
        users_vote = poll.pollvote.filter(voter=request.user)
        if len(users_vote) > 0:
            unit_context['voted'] = True
        polls_context.append(unit_context)
    

polls/templates/polls/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/r.png' %}">
    <title>Error</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand ms-5 pe-3" href="{% url 'homepage' %}"><span class="r">r</span>Polls</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-1">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:browse' %}">Polls</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:create_poll' %}">Create poll</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_all' %}">Forums</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_create' %}">New forum</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:votes_history' %}">Vote history</a>
                  </li>
                </ul>
                <div class="account d-flex me-4">
                    <div class="profile d-flex my-auto me-3">
                        <i class="bi bi-person-circle"></i>
                        <span class="username-viewonly ms-1">{{ username }}</span>
                    </div>
                    <form action="{% url 'logout' %}" method="POST"> {% csrf_token %}
                        <input type="submit" class="btn-1" value="Logout">
                    </form>
                </div>
              </div>
            </div>
          </nav>
    </header>
    <div class="main-container">
        <div class="left-col">
            <div class="recent-polls card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-activity"></i></span>
                    <span class="title">Most Recent</span>
                </div>
                <div class="content">
                    {% for poll in recentpolls %}
                    <div class="poll-item">
                        <a class="poll-title" href="{% url 'polls:polldetails' poll.poll_id %}">{{ poll.poll_title }}</a>
                        <div class="count">
                            <span class="label">vote count:&nbsp;</span><span class="value">{{ poll.vote_count }}</span>
                        </div>
                        {% if poll.vote_count%}
                        <div class="last-vote">
                            <span class="label"><i class="bi bi-check-all"></i></span>
                            <span class="date">{{ poll.last_vote_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ poll.last_vote_voter }}</span>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <a href="{% url 'polls:browse' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
            <div class="community-forum card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-chat-right"></i></span>
                    <span class="title">Forums</span>
                </div>
                <div class="content">
                    {% for forum in forums %}
                    <div class="forum-post">
                        <a class="post-title" href="{% url 'forums:forum_detail' forum.forum_id %}">{{ forum.forum_title }}</a>
                        <div class="last-post">
                            <span class="label"><i class="bi bi-arrow-90deg-down"></i></span>
                            <span class="date">{{ forum.last_post_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ forum.last_post_user }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a href="{% url 'forums:forum_all' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
        </div>
        <div class="right-col">
            <div class="no_access">
                <div class="content">
                    <div class="info">
                        <div><i class="bi bi-exclamation-square"></i></div>
                        <p>{{ error|default:'Error Occurred' }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="upper">
            <div class="col-1">
                <div class="site-name">
                    <span class="r">r</span>Polls</a>
                </div>
            </div>
            <div class="vl"></div>
            <div class="col-2">
                <a href="{% url 'rules' %}">Site Rules</a>
                <a href="{% url 'issue' %}"><i class="bi bi-flag-fill"></i>Report an issue</a>
            </div>
            <div class="vl"></div>
            <div class="col-3">
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'feedback' %}"><i class="bi bi-chat-square-dots-fill"></i>Feedback</a>
                <a href="{% url 'sourcecode' %}"><i class="bi bi-github"></i>Project Sourcecode</a>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/poll_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'images/r.png' %}">
    <title>Poll details</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand ms-5 pe-3" href="{% url 'homepage' %}"><span class="r">r</span>Polls</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item me-1">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:browse' %}">Polls</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:create_poll' %}">Create poll</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_all' %}">Forums</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'forums:forum_create' %}">New forum</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:votes_history' %}">Vote history</a>
                  </li>
                </ul>
                <div class="account d-flex me-4">
                    <div class="profile d-flex my-auto me-3">
                        <i class="bi bi-person-circle"></i>
                        <span class="username-viewonly ms-1">{{ username }}</span>
                    </div>
                    <form action="{% url 'logout' %}" method="POST"> {% csrf_token %}
                        <input type="submit" class="btn-1" value="Logout">
                    </form>
                </div>
              </div>
            </div>
          </nav>
    </header>
    <div class="main-container">
        <div class="left-col">
            <div class="recent-polls card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-activity"></i></span>
                    <span class="title">Most Recent</span>
                </div>
                <div class="content">
                    {% for poll in recentpolls %}
                    <div class="poll-item">
                        <a class="poll-title" href="{% url 'polls:polldetails' poll.poll_id %}">{{ poll.poll_title }}</a>
                        <div class="count">
                            <span class="label">vote count:&nbsp;</span><span class="value">{{ poll.vote_count }}</span>
                        </div>
                        {% if poll.vote_count%}
                        <div class="last-vote">
                            <span class="label"><i class="bi bi-check-all"></i></span>
                            <span class="date">{{ poll.last_vote_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ poll.last_vote_voter }}</span>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <a href="{% url 'polls:browse' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
            <div class="community-forum card">
                <div class="heading">
                    <span class="icon me-1"><i class="bi bi-chat-right"></i></span>
                    <span class="title">Forums</span>
                </div>
                <div class="content">
                    {% for forum in forums %}
                    <div class="forum-post">
                        <a class="post-title" href="{% url 'forums:forum_detail' forum.forum_id %}">{{ forum.forum_title }}</a>
                        <div class="last-post">
                            <span class="label"><i class="bi bi-arrow-90deg-down"></i></span>
                            <span class="date">{{ forum.last_post_time|date:"h:i A, j M o" }}</span>
                            <span class="user">by {{ forum.last_post_user }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <a href="{% url 'forums:forum_all' %}" class="btn-1 link-btn">View All</a>
                </div>
            </div>
        </div>
        <div class="right-col">
            <div class="poll-detail">
                <div class="content">
                    <div class="poll-heading">
                        <div class="banner"><img src="{{ poll_banner_url }}" alt=""></div>
                        <div class="title">{{ poll_title }}{% if editable %}<a href="{% url 'polls:edit_poll' poll_id %}"><i class="bi bi-pencil-fill"></i></a>{% endif %}</div>
                    </div>
                    <div class="pool-info">
                        <div class="pool-choices">
                            <ul class="choice-list">
                                {% for choice in choices%}
                                <li class="choice card-simple">
                                    <div {% if choice.is_voted %}class="choice-text voted"{% else %}class="choice-text"{% endif %}>{{ choice.choice_text }}</div>
                                    <div class="info">
                                        <div class="choice-votes me-2"><span class="label">votes:&nbsp;</span><span class='value'>{{ choice.choice_votes }}</span></div>
                                        <div class="progress">
                                            <div class="progress-bar" role="progressbar" style="width: {{ choice.progressbar_progress }}%;" aria-valuenow="{{ choice.progressbar_progress }}" aria-valuemin="0" aria-valuemax="100">{{ choice.choice_votes_percent }}%</div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="poll-stats card-headless">
                            <ul class="stats">
                                <li>
                                    <span class="label">created by:&nbsp;</span><span class="user">{{ poll_author }}</span>
                                </li>
                                <li>
                                    <span class="label">created at:&nbsp;</span><span class="value">{{ poll_added|date:"h:i A, j M o"  }}</span>
                                </li>
                                <li>
                                    <span class="label">total votes:&nbsp;</span><span class="value">{{ total_votes }}</span>
                                </li>
                                <li>
                                    <span class="label">total views:&nbsp;</span><span class="value">{{ poll_views }}</span>
                                </li>
                                {% if my_vote_time %}
                                <li>
                                    <span class="label">my vote:&nbsp;</span><span class="value">
                                        <span>{{ my_vote_time|date:"h:i A, j M o" }}&nbsp;</span>
                                    </span>
                                </li>
                                {% endif %}
        {% if last_vote_time %} <li>
                                    <span class="label">last vote:&nbsp;</span><span class="value">
                                        <span>{{ last_vote_time|date:"h:i A, j M o" }}&nbsp;</span>
                                        <span>by <span class="user">{{ last_vote_voter }}</span></span>
                                    </span>
                                </li>{% endif %}
                                <li>
                                    <span class="label">active status:&nbsp;</span><span class="value">{{ active_status }}</span>
                                </li>
                            </ul>
                            <div class="share-link">
                                <div class="inner">
                                    <i class="bi bi-share-fill me-2"></i>
                                    <a href="{% url 'polls:polldetails' poll_id %}" id="poll-link">{{ poll_url }}</a>
                                    <button id="ctc">copy</button>
                                </div>
                            </div>
                        </div>
                        {% if votable_status %}<div class="my-action"><a href="{% url 'polls:vote' poll_id %}" type="submit" class="btn-1 link-btn me-1">Vote Now</a></div>{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <div class="upper">
            <div class="col-1">
                <div class="site-name">
                    <span class="r">r</span>Polls</a>
                </div>
            </div>
            <div class="vl"></div>
            <div class="col-2">
                <a href="{% url 'rules' %}">Site Rules</a>
                <a href="{% url 'issue' %}"><i class="bi bi-flag-fill"></i>Report an issue</a>
            </div>
            <div class="vl"></div>
            <div class="col-3">
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'feedback' %}"><i class="bi bi-chat-square-dots-fill"></i>Feedback</a>
                <a href="{% url 'sourcecode' %}"><i class="bi bi-github"></i>Project Sourcecode</a>
            </div>
        </div>
    </footer>
    <script src="{% static 'scripts/ctc.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>